---
- name: Install Nginx on remote hosts
  hosts: all
  become: true 
  tasks:
    - name: Update apt package list 
      apt:
        update_cache: yes
        cache_valid_time: 3600  

    - name: Install Nginx package
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is started and enabled on boot
      service:
        name: nginx
        state: started
        enabled: yes
