- name: Create ECR Repository
  hosts: localhost
  become: true
  vars:
    region: "ap-south-1" 
    name: nginx
  tasks:
  
    - name: install awscli
      command: sudo bash awscli.sh

      
    
     
    
