---
- name: Mount Amazon EFS if not already mounted
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    mount_point: "/efs"
    fsid: "fs-081f6df64ed050884.efs.ap-south-1.amazonaws.com"
                                                     
    fstab_entry: "{{ fsid }}:/ {{ mount_point }} nfs4 defaults,_netdev 0 0"

  tasks:

    - name: Check if the mount point directory exists
      stat:
        path: "{{ mount_point }}"
      register: mount_point_stat

    - name: Create the mount point directory if it doesn't exist
      file:
        path: "{{ mount_point }}"
        state: directory
      when: not mount_point_stat.stat.exists

    - name: Install NFS utilities for Ubuntu/Debian-based systems
      package:
        name: nfs-common
        state: present
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Install NFS utilities for RedHat/CentOS or Amazon Linux
      package:
        name: nfs-utils
        state: present
      when: ansible_distribution == "RedHat" or ansible_distribution == "Amazon"

    - name: Mount the EFS file system
      mount:
        path: "{{ mount_point }}"
        src: "{{ fsid }}:/"
        fstype: nfs4
        opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
        state: mounted
