---
- name: Install and configure Grafana on RHEL-based systems
  hosts: all
  become: true

  tasks:
    

    - name: Copy a file to remote host
      ansible.builtin.copy:
        src: grafana.sh
        dest: /opt

    - name: execute
      command: sh /opt/grafana.sh
