---
- name: List all S3 Buckets
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml  
  tasks:
    - name: List all S3 Buckets
      community.aws.s3_bucket_facts:
        region: "{{ aws-region }}"
        aws-access-key: "{{ aws-accesskey }}"
        aws-secret-key: "{{ aws-secret-key }}"
      register: s3_buckets

    
