---
- name: Install and start Nginx on web servers
  hosts: localhost
  become: yes  
  tasks:
    - name: Install Nginx (Debian-based)
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
