---
- name: List all S3 Buckets
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml  
  tasks:
    - name: List all S3 Buckets
      command: aws s3 ls
        aws-region: ap-south-1
        aws-access-key: "{{ aws-access-key }}"
        aws-secret-key: "{{ aws-secret-key }}"
      register: s3_buckets

    
