# .github/workflows/setup-ssh.yml
name: 'Setup SSH and AWS Credentials'

on:
  workflow_call: # Makes this workflow reusable

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup SSH
        run: |
          if [ -f ~/.ssh/id_rsa ]; then
            echo "File exists"
          else
            mkdir -p ~/.ssh  
            echo "${{ secrets.ssh_key }}" > ~/.ssh/id_rsa 
            chmod 600 ~/.ssh/id_rsa
          fi
