# .github/workflows/setup-ssh.yml
name: 'Setup SSH and AWS Credentials'

on:
  workflow_call: 
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      

      - name: Setup SSH
        run: |
          if [ -f ~/.ssh/id_rsa ]; then
            echo "File exists"
          else
            mkdir -p ~/.ssh  
            echo "${{ secrets.ssh_key }}" > ~/.ssh/id_rsa 
            chmod 600 ~/.ssh/id_rsa
          fi
