name: Remote Deployment

on:
  push:
    branches:
      - main  

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: create repo
           run: aws ecr create-repository --repository-name nginx --region us-east-1

      - name: push to ecr
        run: |
          
          name="nginx"
          region="us-east-1"
          docker build -t $name .
          docker tag $name:latest 585768173504.dkr.ecr.$region.amazonaws.com/$name:latest 
          docker push 585768173504.dkr.ecr.$region.amazonaws.com/$name:latest

          



