name: Remote Deployment

on: 
  push:  
    branches:
      - main  

jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.0'

      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.accesskey }}
          aws-secret-access-key: ${{ secrets.secretkey }}
          aws-region: us-east-1

      


      - name: ssh
        run: |
            mkdir -p ~/.ssh  
            echo "${{ secrets.ssh_key }}" > ~/.ssh/id_rsa 
            chmod 600 ~/.ssh/id_rsa

      - name: SSH into the server and create a directory
        run: |
          
          set +e
          
          region="us-east-1"

          script="abc.sh"
          
          usernames=("ubuntu" "ec2-user" "admin") 

          region="us-east-1"
          
          ips=($(aws ec2 describe-instances --region "$region" --query "Reservations[].Instances[].[PublicIpAddress]" --output text))
          
          
          for username in "${usernames[@]}"; do
 
          for ip in "${ips[@]}"; do

          ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$username"@"$ip" "sudo chmod +x /opt" &> /dev/null   
          
          scp -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa  "$script"  "$username"@"$ip":/opt &> /dev/null

          ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$username"@"$ip" "sudo sh /opt/$script" &> /dev/null
          
          done
         
          done

          

          
        
          
         
          
          

          

          
    
               
  
