name: Remote Deployment

on:  
  push:   
    branches:
      - main  

jobs: 
  checkout-repo:
    uses: ./.github/workflows/checkout-ssh.yml 

  job1:
    runs-on: ubuntu-latest
    needs: checkout-repo 
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   
      - name: Use checked-out code 
        run: |
          sudo chmod 777 ./scripts/awsclirm.sh
          ./scripts/awsclirm.sh                                          
          
          
                          
                                     
                  
          
          
          


          


  
      


      

          
        
          
         
          
          

          

          
    
               
  
