name: Remote Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: ssh
        run: |
            mkdir -p ~/.ssh
            sudo echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            sudo chmod 600 ~/.ssh/id_rsa

      - name: SSH into the server and create a directory
        run: |
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@13.203.198.148 "sudo chmod 777 /opt"
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@13.203.198.148 "sudo touch /opt/abcd.txt"
