name: Remote Deployment 

on:
  push:    
    branches: 
      - main   
   
env:                         
  Region: ap-south-1
jobs: 
  job1:  
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_vers ion: 1.3.0 

      

      


      
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.Region }} 

      - name: role
        run: sh role.sh

          
   
      - name: ssh    
        run: |    
            mkdir -p ~/.ssh   
            echo "${{ secrets.splunk}}" > ~/.ssh/id_rsa 
            chmod 600 ~/.ssh/id_rsa 
 
      - name: script
        run: |
          set +e
           myip="3.110.151.248"
           ebs(){
           usernames=("ubuntu" "ec2-user" "admin") 
           ips=($(aws ec2 describe-instances --region ap-south-1 --query "Reservations[].Instances[].[PublicIpAddress]" --output text))     

           
            
           for username in "${usernames[@]}"; do
 
           for ip in "${ips[@]}"; do

           if [[ "$ip" == "$myip" ]]; then
             
 
           ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$username"@"$ip" "sudo chmod 777 /opt"               
           scp -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$1"  "$username"@"$ip":/opt
           ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$username"@"$ip" "sudo bash /opt/$1"

           break
           fi
           done
           done 
           }
          
           
           scripts=("ansible.sh")
           for script in "${scripts[@]}"; do
           ebs "$script"
           done
        continue-on-error: true 

      - name: ansible
        run: ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa ubuntu@3.110.151.248 "sudo ansible-playbook /opt/ebs.yml"
          
           
           
          

        
            

      
            
            
            
            

            
          


                                            
      
         

      
             

             
             
 

             
           
           

        
         
 
                          
                                     
                  
          
          
          


          


  
      


      

          
        
          
         
          
          

          

          
    
               
  
