name: Remote Deployment

on:  
  push:   
    branches:
      - main  
env:
  AWS_REGION: 'us-east-1' 
jobs:
  checkout-repo:
    uses: ./.github/workflows/checkout-ssh.yml

  job1:
    runs-on: ubuntu-latest
    needs: checkout-repo  # Ensures job1 depends on the checkout-repo job
    steps:
      - name: Use checked-out code
        run: |
          sudo chmod 777 ./scripts/jenkin.sh
          ./scripts/jenkin.sh                                           
          
          
                          
                                     
                  
          
          
          


          


  
      


      

          
        
          
         
          
          

          

          
    
               
  
