name: Remote Deployment

on:  
  push:   
    branches:
      - main 

env:
  Region: us-east-1
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4    
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.Region }} 
      - name: ssh
        run: |
      
            if [ -e ~/.ssh/id_rsa ]; then
            echo "File exists"
            else
            mkdir -p ~/.ssh  
            echo "${{ secrets.ssh_key }}" > ~/.ssh/id_rsa 
            chmod 600 ~/.ssh/id_rsa    
            fi

      
                                     
          
     

      - name: script
        run: |
            
            set +e     
  
             
            usernames=("ubuntu" "ec2-user" "admin")   
          
            ips=($(aws ec2 describe-instances --region ${{ env.Region }}  --query "Reservations[].Instances[].[PublicIpAddress]" --output text))   
          
                  
            for username in "${usernames[@]}"; do
  
            for ip in "${ips[@]}"; do

            ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$username"@"$ip" "sudo chmod 777 /opt"  


            scp -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa  nginx.yml  "$username"@"$ip":/opt

            scp -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa  hosts  "$username"@"$ip":/opt  

            ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$username"@"$ip" "sudo  ansible-playbook /opt/nginx.yml" &> /dev/null

            
            done
      
            done
 
            

            
              
                     



 
                          
                                     
                  
          
          
          


          


  
      


      

          
        
          
         
          
          

          

          
    
               
  
