name: Remote Deployment

on: 
  push:   
    branches:
      - main  

jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: SSH into the server and create a directory
        run: |                                            
          
          set +e
          
          region="us-east-1"
          
          usernames=("ubuntu" "ec2-user" "admin")   
          
          ips=($(aws ec2 describe-instances --region "$region" --query "Reservations[].Instances[].[PublicIpAddress]" --output text))   
          
          packages(){
          for username in "${usernames[@]}"; do
 
          for ip in "${ips[@]}"; do

          ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$username"@"$ip" "sudo chmod 777 /opt" &> /dev/null 

          scp -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa  "$1"  "$username"@"$ip":/opt &> /dev/null 

          ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$username"@"$ip" "sudo sh /opt/$1" &> /dev/null                           
          
          done
         
          done

          }

          scripts=("abc.sh" "mkfl.sh")
          for script in  "${scripts[@]}"; do
          packages "$script"
          done
          
          
          
          
           

          
          
    
            

      
     

      


      

          
        
          
         
          
          

          

          
    
               
  
