name: Remote Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 
      # Log in to AWS ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1 

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t docker build -t nginx .

      # Push the Docker image to ECR
      - name: tag
        run: |
          docker push docker tag nginx:latest 585768173504.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest

      - name: push  
        run: |
           docker tag nginx:latest 585768173504.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest


      - name: ssh
        run: |
            mkdir -p ~/.ssh
            sudo echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            sudo chmod 600 ~/.ssh/id_rsa

      - name: SSH into the server and create a directory
        run: |
         ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@43.204.143.125 "sudo touch /opt/abcd.txt"
