name: Remote Deployment

on:  
  push:   
    branches:
      - main 

env:
  Region: us-east-1
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4    
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.Region }} 
      - name: ssh
        run: |
      
            if [ -e ~/.ssh/id_rsa ]; then
            echo "File exists"
            else
            mkdir -p ~/.ssh  
            echo "${{ secrets.ssh_key }}" > ~/.ssh/id_rsa 
            chmod 600 ~/.ssh/id_rsa    
            fi

      
                                     
          
      - name: script
        run: |
            
            set +e
          
            

            package(){
          
            usernames=("ubuntu" "ec2-user" "admin")   
          
            ips=($(aws ec2 describe-instances --region ${{ env.Region }}  --query "Reservations[].Instances[].[PublicIpAddress]" --output text))   
          
          
            for username in "${usernames[@]}"; do
 
            for ip in "${ips[@]}"; do

            ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$username"@"$ip" "sudo chmod 777 /opt" &> /dev/null 

            scp -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa  "$script"  "$username"@"$ip":/opt &> /dev/null 

            ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$username"@"$ip" "sudo sh /opt/$script" &> /dev/null
  
          
            done
      
            done

               items=("awscli" "banana" "cherry" "date" "elderberry")

              
              for item in "${items[@]}"; do
              case $item in
              awscli)
              package awscli.sh
               ;;
              banana)
             
              echo "This is a banana."
              ;;
              cherry)
             
             echo "This is a cherry."
             ;;
             date)
            
            echo "This is a date."
            ;;
            elderberry)
            
            echo "This is an elderberry."
            ;;
            *)
            echo "Unknown fruit."
             ;;
            esac
            done

                     



 
                          
                                     
                  
          
          
          


          


  
      


      

          
        
          
         
          
          

          

          
    
               
  
