name: Remote Deployment 

on
  push:    
    branches: 
      - main   
   
env:                        
  Region: ap-south-1
jobs: 
  job1:  
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_vers ion: 1.3.0 


      
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.Region }} 

      - name: init
        run: terraform init

        
      - name: terraform plan
        run: terraform plan

      

      - name: terraform destroy
        run: terraform destroy -auto-aprove

      - name: role
        run: sh role.sh
        continue-on-error: true

        


      - name: ssh    
        run: |    
            mkdir -p ~/.ssh   
            echo "${{ secrets.splunk}}" > ~/.ssh/id_rsa 
            chmod 600 ~/.ssh/id_rsa 
 
      - name: script
        run: |
            set +e

            
            ecr(){

            
            username="ubuntu"
          
            ip="15.206.166.129"
          
          

            ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$username"@"$ip" "sudo chmod 777 /opt" &> /dev/null 

            scp -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa  "$1"  "$username"@"$ip":/opt &> /dev/null

            ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "$username"@"$ip" "sudo bash /opt/ansible.sh" &> /dev/null 

            
            }
            scripts=("awscli.sh" "ansible.sh" "Dockerfile" "ecr.yml" "docker.sh")
            for script in "${scripts[@]}"; do
            ecr "$script" 
            done

        continue-on-error: true  
            
      - name: playbook
        run: ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa ubuntu@15.206.166.129 "sudo ansible-playbook /opt/ecr.yml" 

            
            
            
            

            
          


                                            
      
         

      
             

             
             
 

             
           
           

        
         
 
                          
                                     
                  
          
          
          


          


  
      


      

          
        
          
         
          
          

          

          
    
               
  
