name: Remote Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        run: |
            mkdir -p ~/.ssh
            sudo echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            sudo chmod 600 ~/.ssh/id_rsa

      - name: SSH into the server and create a directory
        run: |
         ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@43.204.143.125 "touch /opt/abcd.txt"
