name: Remote Deployment

on:  
  push:   
    branches:
      - main  
env:
  AWS_REGION: 'us-east-1'
jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: pwd
        run: pwd
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: ssh
        run: |
            mkdir -p ~/.ssh  
            echo "${{ secrets.ssh_key }}" > ~/.ssh/id_rsa 
            chmod 600 ~/.ssh/id_rsa    

      - name: SSH into the server and create a directory 
        run: ./scripts/jenkin.sh                                          
          
          
                          
          
          
          
          


          


  
      


      

          
        
          
         
          
          

          

          
    
               
  
